
name: Package addon

on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout addon
        uses: actions/checkout@v1
        with:
          # you can specify how much of the commit history you want to fetch,
          # which is useful for controlling the length of the automated changelog
          fetch-depth: 50

      - name: Luacheck
        uses: BigWigsMods/actions/luacheck@master
        with:
          args: -q
          annotate: warning

      - name: Package and release (TBC)
        uses: BigWigsMods/packager@master
        with:
          args: -g bcc
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}